### ISSUE TITLE
is this code recent and still work ?

### ISSUE THREAD

**Issue by 7c** [Luzifer/espsms#1]
Hello,

i am considering a gsm module, was looking at lilygo but their TinyGSM lib does not support receiving sms. I have looked at your code and seen how "easy" it must be to implement it. I also want to receive sms and forward them to a server. May i ask if your code is working in real environement ?

**Comment by Luzifer** [comment]
The code is 4 years old but the controller worked until recently until I decomissioned the SIM inside and had no further need.
